import { props } from '@webflow/data-types';
import { declareComponent } from '@webflow/react';
import { HeatField } from './HeatField.jsx';
import { PRESET_NAMES } from './heatfield/presets.js';

export default declareComponent(HeatField, {
  name: 'Heat Field',
  description: 'Animated WebGPU contour field with configurable motion and annotations.',
  group: 'Visual',
  props: {
    preset: props.Variant({
      name: 'Preset',
      group: 'Setup',
      options: PRESET_NAMES,
      defaultValue: 'organism',
    }),
    usePresetDefaults: props.Boolean({
      name: 'Use preset values',
      group: 'Setup',
      tooltip: 'Turn off to apply the custom Look, Motion, and Annotation values below.',
      defaultValue: true,
      trueLabel: 'Preset',
      falseLabel: 'Custom',
    }),
    height: props.Number({
      name: 'Height',
      group: 'Setup',
      tooltip: 'Rendered component height in pixels.',
      defaultValue: 600,
      min: 120,
      max: 1600,
      decimals: 0,
    }),
    showStatus: props.Visibility({
      name: 'Show performance',
      group: 'Setup',
      defaultValue: false,
    }),

    bands: props.Number({
      name: 'Bands',
      group: 'Look',
      defaultValue: 8,
      min: 2,
      max: 20,
      decimals: 0,
    }),
    contour: props.Number({
      name: 'Contour',
      group: 'Look',
      defaultValue: 0.92,
      min: 0,
      max: 1,
      decimals: 2,
    }),
    gain: props.Number({
      name: 'Gain',
      group: 'Look',
      defaultValue: 1.1,
      min: 0.3,
      max: 2.5,
      decimals: 2,
    }),
    curve: props.Number({
      name: 'Curve',
      group: 'Look',
      defaultValue: 0.8,
      min: 0.3,
      max: 1.6,
      decimals: 2,
    }),
    outerGlow: props.Number({
      name: 'Outer glow',
      group: 'Look',
      defaultValue: 0.085,
      min: 0.01,
      max: 0.4,
      decimals: 3,
    }),
    falloff: props.Number({
      name: 'Falloff',
      group: 'Look',
      defaultValue: 2.6,
      min: 0.8,
      max: 5,
      decimals: 2,
    }),
    grain: props.Number({
      name: 'Grain',
      group: 'Look',
      defaultValue: 0.02,
      min: 0,
      max: 0.09,
      decimals: 3,
    }),
    anisotropy: props.Number({
      name: 'Anisotropy',
      group: 'Look',
      defaultValue: 1.05,
      min: 0.4,
      max: 4,
      decimals: 2,
    }),

    speed: props.Number({
      name: 'Speed',
      group: 'Motion',
      defaultValue: 1.05,
      min: 0,
      max: 2.5,
      decimals: 2,
    }),
    pulse: props.Number({
      name: 'Pulse',
      group: 'Motion',
      defaultValue: 0.42,
      min: 0,
      max: 0.9,
      decimals: 2,
    }),
    travel: props.Number({
      name: 'Travel',
      group: 'Motion',
      defaultValue: 0.18,
      min: 0,
      max: 0.6,
      decimals: 2,
    }),
    warp: props.Number({
      name: 'Warp',
      group: 'Motion',
      defaultValue: 0.075,
      min: 0,
      max: 0.25,
      decimals: 3,
    }),
    warpFreq: props.Number({
      name: 'Warp frequency',
      group: 'Motion',
      defaultValue: 2.8,
      min: 0.5,
      max: 6,
      decimals: 1,
    }),
    nodes: props.Number({
      name: 'Nodes',
      group: 'Motion',
      defaultValue: 34,
      min: 4,
      max: 320,
      decimals: 0,
    }),

    labels: props.Number({
      name: 'Labels',
      group: 'Annotations',
      defaultValue: 5,
      min: 0,
      max: 6,
      decimals: 0,
    }),
    connectors: props.Number({
      name: 'Connectors',
      group: 'Annotations',
      defaultValue: 2,
      min: 0,
      max: 3,
      decimals: 0,
    }),
    rings: props.Boolean({
      name: 'Rings',
      group: 'Annotations',
      defaultValue: true,
      trueLabel: 'Show',
      falseLabel: 'Hide',
    }),
    ringSize: props.Number({
      name: 'Ring size',
      group: 'Annotations',
      defaultValue: 1.45,
      min: 0.6,
      max: 3,
      decimals: 2,
    }),
    spin: props.Number({
      name: 'Ring spin',
      group: 'Annotations',
      defaultValue: 0.075,
      min: 0,
      max: 0.4,
      decimals: 3,
    }),

    seamless: props.Boolean({
      name: 'Seamless loop',
      group: 'Loop',
      defaultValue: true,
      trueLabel: 'Seamless',
      falseLabel: 'Free-running',
    }),
    loopLength: props.Number({
      name: 'Loop length',
      group: 'Loop',
      tooltip: 'Loop duration in seconds.',
      defaultValue: 20,
      min: 4,
      max: 60,
      decimals: 0,
    }),

    renderScale: props.Number({
      name: 'Render scale',
      group: 'Performance',
      defaultValue: 1,
      min: 0.35,
      max: 1,
      decimals: 2,
    }),
    fieldScale: props.Number({
      name: 'Field scale',
      group: 'Performance',
      defaultValue: 0.5,
      min: 0.2,
      max: 1,
      decimals: 2,
    }),
  },
  options: {
    ssr: false,
  },
});
